language: node_js
node_js :
 - "node"
after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: never
services:
 - postgresql
before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'test';" -U postgres
  - psql -c "ALTER DATABASE test_db OWNER TO tester;" -U postgres
