language: node_js
node_js :
 - "node"
after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: never
services:
 - postgresql
before_script:
  - psql -c 'CREATE DATABASE login;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres
  - psql -c 'ALTER DATABASE login OWNER TO admin;' -U postgres
